thresholds:
  P1_T: 20000
  P1_delegate_wait_h: 24

activities:
  TARGET_ACTS: ["O_ACCEPTED", "A_APPROVED"]
  APPROVAL_ACTS: ["W_Validate application", "W_Complete application", "A_Accepted", "O_Create Offer"]
  REQUEST_ANCHORS: ["A_SUBMITTED"]

roles:
  senior_regex: "(?i)(SENIOR|MANAGER)"

defaults:
  timezone: "UTC"
  unknown_role_is_junior: true
